### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by eruido** [PieterCooreman/QuickerSite#2]
Hi
Im running IIS EXPRESS IN A w10 pc.

I did follow instructions. The website starts. And then I get this message when browse i for first ime.

ADODB.Recordset error '800a0e7d'

The connection cannot be used to perform this operation. It is either closed or invalid in this context.

/asp/includes/languageInit.asp, line 13

Hope it is some detail I missed.
Thanks!

**Comment by PieterCooreman** [comment]
Hi this usually indicates a incorrect path to the database files in /asp/config/web_config.asp

Can you check the path in  C_DATABASE and C_DATABASE_LABELS ? You may have to set the virtual directory in C_VIRT_DIR and C_DIRECTORY_QUICKERSITE

**Comment by eruido** [comment]
Thanks Pieter!
Finally I felt that this was something to do with drivers, so I followed this hint

https://docs.microsoft.com/en-us/iis/application-frameworks/running-classic-asp-applications-on-iis-7-and-iis-8/using-classic-asp-with-microsoft-access-databases-on-iis

And got this tweak for Quickersite App pool

Working with 64-bit Systems
Unfortunately there are no 64-bit ODBC drivers, so on 64-bit systems you will have to run your applications in 32-bit mode. To do so, use the following steps:

On the taskbar, click Start, point to Administrative Tools, and then click Internet Information Services (IIS) Manager.
In the Connections pane, click Application Pools.
Highlight the application pool for your application, then click Advanced Settings... in the Actions pane.
In the Advanced Settings dialog, specify True for Enable 32-Bit Applications.
Click OK to close the Advanced Settings dialog.

No I have a login window. :)

Do you mind posting some steps to use SQL Server as backen? Is there a sql bootsrap script to create such database ? That would make easier for me for production use. 

Thanks  for your work !!I hope we will help in any way we can.

**Comment by PieterCooreman** [comment]
Hi, I was assuming 32bit applications were enabled by default in IIS Express... apparently not. The instructions you post are only valid for IIS though, not IIS Express btw :) IIS Express has no managing panel.

For QS there is no reason to upsize to SQL Server, not even for big or busy sites. I have used Access database on very crowdy sites in the past. No problems at all. Even when using SQL Server in QS, you would still need to access the labels database, so you would always need to enable 32 bit applications in IIS. 

Hope this helps.

**Comment by eruido** [comment]
ok. I am using IIS in W10. It has MMC console so it is IIS (not express I Guess). 32 bits apps where not enabled by default, and that config change made Quicker run ok.
The CMS runs like a charm, really fast and friendly. It is much more than a CMS, it is a whole platform / framework. Great work though!
I always thought of some ASP solution that could run parameterized VB code as.part of a CMS, and You did it. It's really simple to use it by any seasoned Classic ASP programmer.
We use Mobirise for our landing page, so next step Will be to learn how to generate templates for Quickersite using our current page design.
About sql server, it si not a matter of performance, it is because que have all our backup chain already Made for sql server and that allows us to get to production faster. Even if I have made quite some production sites based on Access we don't have now a production backup chain for that. but we can make it if needed.  I love Access by the way.

**Comment by PieterCooreman** [comment]
Access has an upsize wizard to SQL Server. After the upsize, make sure to modify the parameters
'QS_DBS			= 2					'2 for SQL Server 2000/2005
'SQL2005_SERVER	= ""				'server
'SQL2005_DB		= ""				'database
'SQL2005_UID	= ""				'user
'SQL2005_PWD	= ""				'password

in /asp/config/web_config.asp
